### ISSUE TITLE
Feature request: export into STDOUT

### ISSUE THREAD

**Issue by oleksandr-kuzmenko** [bitwarden/cli#103]
It would be great to be able to send the output of the `export` command to `stdout`, not in file. I would like to improve the security of my export data, and not store unencrypted passwords on the disk for a second.

For example, something like this: `bw export | gpg`.

If you are OK with this feature, I can try to send PR.

**Comment by shello** [comment]
Not being able to output data to STDOUT makes composing `bw export` in any manner very difficult, which is a rather frustrating experience for a CLI tool.

To make matters worse, from what I can tell the function being used to write the file underneath is `fs.writeFile()`, which seems to fail to write to anything that's not an actual file; that means that trying to work around this limitation in `bw export` using process substitution, or even named pipes ("FIFOs") passed to `--output` is not a possibility because how nodejs seems to handle writes.

Being able to pass `-` to `--output` to signify "write to fd 1" (or even having a different argument to force the export output to STDOUT instead of a file...) would make `bw export` a much better CLI citizen.

**Comment by yourfate** [comment]
Yes, I would also love this feature, so I can for example pipe the output directly into my backup tool which encrypts it and stores it securely, without ever having an unencrypted copy in the file system.

**Comment by ajstiles** [comment]
One some platforms you can use `/dev/stdin` for the file path. Combine that with `--quiet` (suppresses the success message), and I think that gets you what you are looking for @shello, @alxpy, @yourfate.

`bw export --quiet --output /dev/stdin`

I looked at how Commander processes arguments and couldn't find a quick way to allow it to accept `-` to represent STDOUT.

**Comment by shello** [comment]
@ajstiles I appreciate the suggestion. This was one of the first things I tested, as it is the simplest workaround that usually works for other programs with this limitation.
Unfortunately (at least for me, on Linux) it does not work for `bw`, resulting in an error `Cannot save file to /dev/stdout` (which is suppressed by `--quiet`). That is the same behaviour that shows up when passing anything that is not a regular file (or an empty path) to `--output`. 

Out of curiosity, on which platforms supported by `bw` will `bw export --output /dev/stdout` work?

**Comment by ajstiles** [comment]
I overstated, should have said platform. It worked for me on Mac.

I wonder if `/proc/self/fd/1` would work instead of `/dev/stdout`.

**Comment by 2bithacker** [comment]
Just tested on Ubuntu 19.10 with `--output /proc/self/fd/1` and it acts the same as `/dev/stdout`, resulting in `Cannot save file to /proc/self/fd/1`.

**Comment by shello** [comment]
This issue can be closed (as well as PR #116 ?), as exporting to STDOUT was implemented back in August 25th with commit f2530c1 (v1.12.1).

As described in PR #152:
> [...] since raw output of the filename is not really that helpful for these cases, I modified the flow so that the combination of no explicit output being given (`--output` is omitted) and `--raw` being specified, leads to the content being written to stdout.

Using @alxpy's example on the first post, exporting directly to `gpg` is done with: `$ bw export --raw | gpg ...`.
