### ISSUE TITLE
Feature request: Support for BSD? 

### ISSUE THREAD

**Issue by iah** [bitwarden/cli#113]
Hi,
I have been searching a lot for bitwarden and usage on BSD but found nothing. Is there any support or maybe someone able to make it work on BSD? For example OpenBSD and FreeBSD? Thanks in advance!

**Comment by kspearrin** [comment]
We don't have a compiled binary for BSD. Can you use it via `npm`?

**Comment by iah** [comment]
> We don't have a compiled binary for BSD. Can you use it via `npm`?

Yes, I suppose I can. But would in the best possible world not use node. Is there a way I could help you with porting bw to openbsd?

**Comment by xale** [comment]
Big ol' +1 here.

I'm trying to set up a backup system for my vault using a jail on my TrueNAS server, but `npm` is a non-starter.

**Comment by 0mp** [comment]
It would be great if Bitwarden distributed binaries native for other operating systems like FreeBSD.

In the meantime, I've created a package of Bitwarden CLI for FreeBSD, which ships the Linux binary. It's possible for FreeBSD users to use it because of the Linux binary compatibility layer in FreeBSD (FreeBSD can execute Linux binaries).

Here's an overview of the port: https://www.freshports.org/security/linux-bitwarden-cli/

Cheers!

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
