### ISSUE TITLE
Failed sync reported as successful

### ISSUE THREAD

**Issue by paescuj** [bitwarden/cli#12]
Since I'm using bitwarden in conjunction with a self signed certificate the sync doesn't work (without the workaround mentioned in #9).
However it is still reported as successful:
```bash
$ bw sync --session ***
Syncing complete.
```
Interestingly, the last sync date is correct / doesn't get updated:
```bash
$ bw sync --last --session ***
2018-05-28T15:49:04.015Z
```

**Comment by edermi** [comment]
I stumbled across the same issue and can confirm this issue. I would expect the CLI to print an error message like the log-in function already does.

**Comment by kspearrin** [comment]
I'm curious how you were able to log in and obtain a session without a cert issue in the first place?

**Comment by edermi** [comment]
`NODE_EXTRA_CA_CERTS=<path to my ca> bw login` from #9 works, but without the environment variable  there is an error stating that the cert is self-signed. `bw sync` won't report this error and falsely state that the sync was successful. Using `NODE_EXTRA_CA_CERTS=<path to my ca> bw sync` works correctly

**Comment by team-tooling** [comment]
We can confirm the same issue. Another hack to make it work is to set the environment variable:
```NODE_TLS_REJECT_UNAUTHORIZED=0```

Since this product is specifically in the security domain, we would not expect workarounds regarding chains of trust to get it to actually work.

The first fix should be to get an error code and message when a sync fails, that should be easy enough?
