### ISSUE TITLE
Lock/Unlcok with custom password/pin

### ISSUE THREAD

**Issue by dac73** [bitwarden/cli#134]
Looks like this is not supported, but could it be possible to use custom pin/password for lock/unlock (like we have for desktop app/browser extension)?

Since my master password is kinda huge, I would like to have shorter local password for CLI?

**Comment by timcappalli** [comment]
On Windows and macOS, it would be awesome to be able to use Windows Hello / Touch ID to unlock, with a PIN fallback.

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by the-rene** [comment]
Google search showed me this issue, here is the Link to a feature request in the mentioned forum to make it more visible for the people who followed/voted on the issue: https://community.bitwarden.com/t/re-use-desktop-authentication-in-cli/39803
