### ISSUE TITLE
[Feedback from LastPass convert] CLI usability / wish-list

### ISSUE THREAD

**Issue by wkoszek** [bitwarden/cli#141]
Hi folks

Below I'm typing some notes as a possible LastPass convert. More of a feedback, but some stuff I've found surprising. I'm running:

```
$ bw -v
1.10.0
```

I do:

```
bw list

  error: missing required argument `object'
```

It'd be nice if, for the usability sake, this stuff just guided me with messages on what I can list.

CLI as it is now, appears to be just a little more than `curl`. It's so-so useful for just working with this stuff. I do:

```
bw list collections
```

and it spits our compressed JSON, not even prettified. I need to pipe everything to "jq" to really read it. It should just be ASCII, maybe until I request JSON explicitly.

`lpass login <email>`

gives me a session that is up and running. With `bw login` I need to fiddle with env. variables to actually make it work.

Examples are ... interesting:

```
    bw create folder eyJuYW1lIjoiTXkgRm9sZGVyIn0K
```

This, I guess, is base64, but it's nowhere explained. Also it's unclear why would anyone want to be typing JSON into the CLI. `lpass` has a decent CLI -- try it out for inspiration. IMO it should be:

```
bw create folder My_Folder
```

I'm here b/c we consider switching to LastPass. I have N interns, where N is large. What I'm wondering is how onboarding on BitWarden could be handled for them.

What I need is:

```
#!/bin/sh
# This script onboards a user $1==user email, $2==user name
UEMAIL=$1
UNAME=$2
bw login <myadminemail>
bw user add $UEMAIL
bw create collection adam_$UNAME
bw collection -u $UEMAIL adam_$UNAME
bw create item -c adam_$UNAME -f aws/$UNAME aws_creds # AWS creds file dumped from AWS console
bw create item -c adam_$UNAME -f ssh/$UNAME ssh_keys # SSH file which I'd like this person to use
```

**Comment by kspearrin** [comment]
Have you read the documentation for the CLI? All of these questions are covered there.

**Comment by wkoszek** [comment]
@kspearrin If you read my feedback again you'll see there are no real questions here -- just feedback. I'm sure I can make it all work. It'll just take twice as long. IMO if folks want to pass JSON, they should just use REST API in their favorite programming language. For me to onboard my employees quickly to BitWarden I kinda want simple CLI that doesn't require `base64', `jq` and formulating JSON in the shell. That's what my feedback is all about.

**Comment by jarbus** [comment]
To tack onto this, bitwarden-cli for me is almost unbearable as a lastpass convert. With lastpass, I could list all the websites I can search without all the extra json and pipe it into a dmenu script. I can use dmenu to select the website, then request said website from lastpass and copy the password to the clipboard. The reason why this is a big deal is because if I need to choose between two different logins for the same site, `bw get` is pretty much useless.

Core example, and the reason why I am here: I do `bw get password facebook`  and it returns two unreadable IDs, which correspond to oculus and facebook. ('facebook' returns both sites, but 'facebook.' doesn't)

The ability to list websites in a human readable fashion should be a core part of bitwarden-cli.

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
