### ISSUE TITLE
[Request] option to turn off color

### ISSUE THREAD

**Issue by ElTopo** [bitwarden/cli#143]
bw may work perfectly in white-on-black terminal, but the colored text could be hard to read in some light-theme terminals, for example, here's a screenshot:

![Screenshot - 6_8_2020 , 1_21_03 PM](https://user-images.githubusercontent.com/217195/84076780-3f8d6200-a98b-11ea-8b5b-575cf4a8eb57.png)

Can we have a command-line option to turn off color (such as --nocolor, or config color off)?

Thanks.

**Comment by clayadams5226** [comment]
Hey @ElTopo , We use GitHub issues as a place to track bugs and other development-related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
