### ISSUE TITLE
[feature request] shell completion for fish shell

### ISSUE THREAD

**Issue by egeland** [bitwarden/cli#148]
It would be really great to have something like `bw completions fish` output what fish needs for completions.

As a bonus, `bw completions bash` could do the same for bash shell..

Any takers?

**Comment by cscharf** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
