### ISSUE TITLE
Query using multiple search terms? (boolean AND)

### ISSUE THREAD

**Issue by luckman212** [bitwarden/cli#163]
I know how to use the CLI to search for a single term e.g.
```
bw list items --search msft
```
but it seems there is no way to enter >1 keyword. E.g.
```
bw list items --search msft acme
```
fails to return any results. I also tried some variations (doesn't work either)
```
bw list items --search msft,acme
bw list items --search "msft acme"
```
This is maybe ok for small vaults with just a few dozen passwords, but I have 650 items in mine. Is there any plan to allow boolean AND joined search?

**Comment by cscharf** [comment]
Hi @luckman212 , thanks for the request!

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by luckman212** [comment]
Ok. https://community.bitwarden.com/t/cli-query-using-multiple-search-terms-boolean-and/15337
