### ISSUE TITLE
[FeatureRequest] download via winget

### ISSUE THREAD

**Issue by rockaut** [bitwarden/cli#174]
It would be great if we could download and install on windows with winget. Please ... pretty please?

**Comment by Greenderella** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.
 
Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

Thanks!
