### ISSUE TITLE
FEATURE REQUEST - inspect environment variable to use a pinentry program for entering password

### ISSUE THREAD

**Issue by jcolson** [bitwarden/cli#182]
would be great if bitwarden inspected an environment variable such as lastpass-cli's LPASS_PINENTRY to exec a GUI pinentry for password entry for 'login' or 'unlock'.

**Comment by Greenderella** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.
 
Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

Thanks!

**Comment by jcolson** [comment]
@Greenderella  - done here -> https://community.bitwarden.com/t/inspect-environment-variable-to-use-a-pinentry-program-for-entering-password

closing here.
