### ISSUE TITLE
Don't read secrets as cli arguments

### ISSUE THREAD

**Issue by rpdelaney** [bitwarden/cli#195]
```console
$ bw login --help
Usage: login [options] [email] [password]

Log into a user account.
```

In many POSIX-like operating systems, command-line arguments passed to a running process can be read by any user. It is usually extremely cheap to do this, which entails a vulnerability to process monitoring on multi-user systems.

Instead, for supporting non-interactive use of bitwarden-cli, read the password from an environment variable or from STDIN. This would allow me to keep the password in a file on-disk that only my user can read, without risking exposure to any other user. For example, it could look something like:

```console
$ cat mysecretkey
SUPERsecretPASSWORD
$ bw login me@myemail.com < mysecretkey
````

Or:

```console
$ cat mysecretenv
export BW_PASSWORD="SUPERsecretPASSWORD"
$ source mysecretenv
$ bw login me@myemail.com
```

**Comment by rpdelaney** [comment]
This also goes for commands that take a `--session` parameter.

**Comment by rpdelaney** [comment]
I might add that aggressive logging is common in automated systems, so this also increases risk that a secret will be logged unintentionally.

**Comment by clayadams5226** [comment]
Hi @rpdelaney, thanks for the feedback. 

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
