### ISSUE TITLE
Cannot export BitWarden vault non-interactively

### ISSUE THREAD

**Issue by baynezy** [bitwarden/cli#200]
In the [documentation](https://bitwarden.com/help/article/cli/) is says you can do the following:-

```bash
bw export myPassword321 --output ./my_backup.json --format json
```

However, it always prompts me for a password. My goal is to run this non-interactively, and so the prompt breaks my script.

**Comment by aramaki87** [comment]
I have the same problem at the moment. I fixed it with the following bash script:
I know I know... but it works =)


#!/bin/sh
bw login networkopercenter@chmedia.ch yOuRpAsSwOrD
printf '%s\n%s\n' "yOuRpAsSwOrD" "yOuRpAsSwOrD" | bw export yOuRpAsSwOrD --format csv

**Comment by 739918602** [comment]
+1

**Comment by 739918602** [comment]
add parameter --session like this:
```
bw export $PASSWD --session $BW_SESSION
```

**Comment by mattcen** [comment]
It seems silly to require a password at all for an export. Prompting for a password that outputs *all* passwords in plain text *does* make sense, but `bw list items` has very similar output to `bw export --raw --format json`, which also outputs all passwords, but does *not* prompt for the password if you have a valid `$BW_SESSION`.

Am I missing something here, or is really contradictory? Either prompt for a password in both cases, or not at all?

**Comment by gboder** [comment]
I'm looking for a way to export the whole vault content to achieve a disaster-recovery backup outside of the Bitwarden SaaS infrastructure. I was going for a scheduled Azure Function using a PowerShell script and a customized Docker container. However, this whole procedure is by design non-interactive and therefore any interactive prompts are true blockers.

I agree with @mattcen either always or never - I would tend towards always to support automated backup-scenarios.

What the options here?

**Comment by eliykat** [comment]
This has also been reported in #232, and that Issue has more detailed discussion, so I'll close this as the duplicate. Please continue any discussion in #232.
