### ISSUE TITLE
bw login failed, reason: self signed certificate

### ISSUE THREAD

**Issue by darton** [bitwarden/cli#236]
./bw login
request to https://servername/api/accounts/prelogin failed, reason: self signed certificate

**Comment by kendratodd** [comment]
Hi @darton! Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
