### ISSUE TITLE
Brew does not install bitwarden without any errors

### ISSUE THREAD

**Issue by TylerAff** [bitwarden/cli#240]
I tried to installed bitwarden via brew but I got the following error:

curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
Error: Failed to download resource "icu4c"
Download failed: https://homebrew.bintray.com/bottles/icu4c-68.2.catalina.bottle.tar.gz

I am running on Mac Catalina 10.15.7

**Comment by onedr0p** [comment]
It's probably better to brew install node and then install bw cli with npm as defined in the docs.

**Comment by MGibson1** [comment]
This doesn't look like anything to do with the brew formula, which is here https://github.com/Homebrew/homebrew-core/blame/03477df81471d144029006995c8607cf8b20b3c2/Formula/bitwarden-cli.rb. The formula basically just installs via npm.

It looks to me like something with you local system having trouble installing icu4c. In itself this is odd since I don't see that in our dependency tree. At any rate, please try downloading again. The formula was updated 10 days ago to point to the latest release.

I'm going to close this issue. If you still feel this is something wrong with the Bitwarden CLI, please reopen
