### ISSUE TITLE
Fish completion support

### ISSUE THREAD

**Issue by onedr0p** [bitwarden/cli#263]
Related #75 #257

**Comment by MGibson1** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a section for submitting, voting for, and discussing product feature requests like this one.

Please sign up on our forums and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by onedr0p** [comment]
@MGibson1 please create a ISSUE_TEMPLATE with a link to the bitwarden forum... You can copy something like I've done here and add a link to the BW forums on feature requests. This will help people direct issues where they need to go.

https://github.com/k8s-at-home/charts/tree/master/.github/ISSUE_TEMPLATE
