### ISSUE TITLE
Maximum Access Count

### ISSUE THREAD

**Issue by luckman212** [bitwarden/cli#265]
`bw send` is an amazingly useful addon! Thank you 🎉 

Sorry if this is a duplicate (I searched...) but, is it planned to add the _Maximum Access Count_ feature flag to the CLI?

![image](https://user-images.githubusercontent.com/1992842/112677099-abb85400-8e3f-11eb-8ebc-1a40fb3d5c7e.png)

**Comment by MGibson1** [comment]
The current construction of the CLI is primarily to rely on passing encoded json objects to the CLI to save/update objects.

Max Access Count can be accessed through these means. I like to call this "advanced" send creation as opposed to the "simple" creation afforded by `bw send "some text"`.

In order to update max access count, you'd do something like:
```
bw send template send.text | jq '.name="send name" | .maxAccessCount=3 | .text.text="The text to send" | .notes="" | .password="good-battery-horse-staple"' | bw encode | bw send create
```

That being said, yes I plan on adding more options to the "simple" create as people ask for them. If this is a high-traffic feature, it'll be added ;)

**Comment by luckman212** [comment]
Got it, didn't know you could manipulate the json object like that. Fair enough, thank you for the help.

**Comment by luckman212** [comment]
@MGibson1 got it working, but- #268 is that a bug or a feature?

**Comment by MGibson1** [comment]
Glad you got things working. I'll answer over there
