### ISSUE TITLE
login problems

### ISSUE THREAD

**Issue by cdornan** [bitwarden/cli#266]
Please note that my reason for me moving away from competing products is that Bitwarden is an open source project, it has come highly recommended form other serious open source advocates and that it is clearly of high quality with comprehensive API support. Thank you for this beautiful set of tools.

That said, I think that there does seem to be some issues with the login API and the distribution of unpackaged binaries.

I have spent most of the day genuinely but eroneously concerned that something nasty was afoot while trying to get going with `bw`. A number of factors were combining to unsettle me, unfamiliar as I was with Bitwarden in general.

  1. Trying to download the executable directly from the main download page on Big Sur -- the first option -- was problematic as Big Sur really, really does not want to run unsigned executables downloaded from the internet. It seems to me that Big Sur is wholly right on this count and I was immediately confused to find Bitwarden choosing this as the primary method for distributing `bw`. (When I eventually plucked up the courage, I loaded it into Text, overriding macOS malware warnings, and then switched to the command line to run it; this was to check against what I was seeing in the Homebrew/NodeJS distros.)
  2. The first [listed method for logging in](https://bitwarden.com/help/article/cli/#logging-in) is to pass the master password on the command line but this is a really bad idea as the command line could be sniffed by another process -- command lines are shown by ps, top etc. -- and, more seriously, get copied into history files. OpenSSL, ssh and of course GnuPG go to great lengths to avoid this (as would a fix to #65 of course). I would never generally put such a secret on a command line so I avoided this altogether in favour of using `--apikey`, thereby losing access to insights I would have gained from trying it out. (Finally, out of desparation I did it anyway, of course, knowing I would discard everyting and start over with a fresh mp.)
  3. The documentation for `--apiky` is not clear for somebody coming to this for the first time. The `Session Management`/`Logging In` says at the end,
> After successfully logging into the CLI a _session_ key will be returned. This session key is necessary to perform any commands that require your vault to be unlocked (list, get, edit, etc.).
I took this to mean that I should `bw` should spit out a session after a successful `login --apikey`, but of course it cannot. I understand this now but not then. it does say 'For more information, see Personal API Key for CLI Authentication' but I assumed that would tell me about `client_id` and `client_secret` for which I didn't believe I needed an explanation. In that section it said 
> Once you enter these values, enter your Master Password to decrypt your Vault.
which was quite opaque. Of course I now know that I need to perform a command like `unlock` to trigger bw to decrypt the vault, establish the session key and print it out to me.
  4. The phrasing is not as clear as it could be when it comes.
> To unlock your vault, set your session key to the `BW_SESSION` environment variable. ex:
$ export BW_SESSION="&langle;session key&rangle;"
> $env:BW_SESSION="&langle;session key&rangle;"
These look like generic instructions with dummy data. Wouldn't it be clearer if there was a clear statement that "Your session key is &langle;session key&rangle;". This is more of a quibble but it added another layer of uncertainty.

I did try to get this clarified in the three listed support channels &mdash; discourse, reddit and twitter &mdash; but only got a response on twitter to say that they could not reproduce. I emphasised that I was looking for the session key from the "login --apikey" command, listing its outputs, but still no clarification was offered. I feel sure that the lack of response was not unhelpfulness but a general lack of clarity in the way login should work.

Shouldn't `--apikey` be the preferred method for logging in?  In which case shouldn't that be the primary method deserving a clear, dedicated step-by-step explanation in the docs?

**Comment by cdornan** [comment]
Thinking about it, is there a reason why login does not read the master passwowrd and setup the session? If there are such use cases then could you make the default action to set up the session with an option to defer?

**Comment by MGibson1** [comment]
Thanks for these notes on documentation. I'm pinging our docs-guru @fschillingeriv to take a look at your suggestions and improve where necessary.

The preferred login method for someone with your concerns about `ps` sniffing and bash history would be to just use `bw login`. In which case, you will be prompted for your email/password. If you are using `bw` as a script and cannot interact, you can pass in your password as an environment variable or as a file location.

As for session management. It is a security feature to require some session information in order to operate and it is not possible to globally set this environment information from within the application across all OSes we support.

The session management output you quote is a set of instructions and examples on how to set you session environment variable. You can copy-paste the appropriate example to set the BW_SESSION environment variable in your command line session and not have to deal with it. You can also pass `--session <session_key>` to each `bw` command. Could you specifically let me know what is unclear or confusing about the output?

Finally, if you want the `bw login` command to just return the required session key, use the `--raw` option (`bw login --raw`) to have JUST the session key returned. You could store this in a variable in a script and use the aforementioned `--session` option everywhere else.

BTW, Our official support channel is though contacting us on our `contact us` page, https://bitwarden.com/contact/.

**Comment by cdornan** [comment]
I am sorry, I went to your help page and moved to the bottom to the 'Connect with US' section which I took to be your support channels. I will bear email in mind.

I do appreciate this product. My whole critique is the first impression that you could be making on a new user and how easy it is for a new user to get derailed by the current presentation. Once I understood what was going on, of course I immediately cut and paste the `SESSION_ID` setup &mdash; that works very nicely. My point is that you relly might as well state that "you session-id is foo". Once ypou know it all makes sense -- which is why I raised this issue so that you can see what can happen when you don't know how it all fits together, information that you could be missing.

Is there a reason for having `--apikey`? It seems redundant.

Thanks again for the excellent tools.

**Comment by MGibson1** [comment]
I hear you, thank for the suggestions. It sounds like we should shore up documentation around logging in. Maybe write a blurb under [session management](https://bitwarden.com/help/article/cli/#session-management) explaining the story of logging in, since it's really a multi-step process.

The `apikey` flag is exists for a few reasons:
1. It allows you to authenticate without full knowledge of the account your authenticating in the event of some data leakage
2. It allows you to revoke access to a device by rotating your api key
3. It logs in without requiring master password, which opens access to a few CLI features that are unavailable to instances that aren't logged in.
