### ISSUE TITLE
bw config server

### ISSUE THREAD

**Issue by r3k2** [bitwarden/cli#275]
Hello, 
I was testing the bw CLI and I though bw config server was to do something else and I overwrote it, now I want to change it back to the default but, I can't see to find nowhere this setting... I searched duckduckgo for "bitwarden default vault server" with no success I keep getting self hosted documentation.
Thanks

**Comment by eliykat** [comment]
`bw config server bitwarden.com` should reset it to default values (see the example in `bw config server --help`, although I admit it's not expressly stated).

If you need any further help, please get in touch with our customer success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed.
