### ISSUE TITLE
bw send create <encoded json> ignores --fullObject flag and `.notes` for file types (type==1)

### ISSUE THREAD

**Issue by luckman212** [bitwarden/cli#305]
### Simple repro:

```bash
bw send template send.file |
jq --arg f "testfile.pdf" '.notes="my note" | .type=1 | .file.fileName=$f' |
bw encode |
bw send create --fullObject
```

### bug 1 - output is plaintext when it should be JSON:
```
Send created! It can be accessed at:
https://send.bitwarden.com/#-xxxxxxxxxxxxxxxxxxxxxxx
```

### bug 2

when clicking the URL, the `"my note"` text is not shown.

**Comment by MGibson1** [comment]
### issue 1
`--fullObject` has been addressed and is fixed with #285 

### issue 2
I believe the second is a misunderstanding of the notes field. These notes are not shown on to the receiver of the send -- that's only the file. The notes are for the creators benefit and can be seen when running, for example
``` bash
bw send get testfile.pdf | jq
```
in the `notes` field.

Currently, no user-determined text information is presentable to the receiver in File type sends.

I'm going to close this issue given the above. If you still have concerns, feel free to reopen.

**Comment by luckman212** [comment]
Thanks @MGibson1 - ok so we just need to wait for the next public release for the changes in #285, right? 

As for the `notes` - that makes sense. So if we want to put a short message for the recipient alongside a file send, we should use the `.name` attribute I guess? (seems the be the only one that's publicly displayed)

**Comment by MGibson1** [comment]
Yeah, I think that's the way to.

I suppose since you're writing a script you could make a text send with your information that also contains a link to a file send you create. Not a great user experience with that since it's multiple hops and the link won't be hyperlinked.
