### ISSUE TITLE
Why can't custom fields be accessed directly using the get command

### ISSUE THREAD

**Issue by jakubgs** [bitwarden/cli#313]
The `get` command returns values for some fields:
```
 > bw get username my-super-secret-secret     
SECRET
```
But if I try to access a custom text field in that entry I get nothing:
```
 > bw get custom-field my-super-secret-secret     
Unknown object.
```
Why is that?

**Comment by ggiesen** [comment]
I'm not the developers, but according to the `bw get --help` output, bw only support retrieving the following fields with get:

    item
    username
    password
    uri
    totp
    exposed
    attachment
    folder
    collection
    org-collection
    organization
    template
    fingerprint
    send

I'm guessing you're probably aware that you can retrieve them by getting the item and then parsing the JSON output.

**Comment by kendratodd** [comment]
+1 to @ggiesen's suggestion of parsing the JSON output 👍  Also, @jakubgs, you're very welcome to start this topic as a feature suggestion in our community forum if this is something you'd like to see added to CLI!

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
