### ISSUE TITLE
Assign org collection to an item

### ISSUE THREAD

**Issue by alancivita** [bitwarden/cli#322]
Can someone explain and clarify how to assign a collection to an item in my orgusing the CLI? i cannot figure out 

so, through the web interface, i've created a new item and assigned ownership to my Org. By default if the item is owned by an Org you have to assign a collection. After creation i've removed the item from the collection.

Now i'd like to assign a collection to that item:
bw list item:
{"object":"item","id":"e4a8bb02-3696-4664-978d-ad3d01293bc8","organizationId":"xxxxxxxxxxxxxxx","folderId":null,"type":1,"name":"zzz","notes":null,"favorite":false,"login":{"username":"zzz","password":"zzz","totp":null,"passwordRevisionDate":null},"collectionIds":[],"revisionDate":"2021-06-04T18:02:11.646Z"}]

 bw list collections
[{"object":"collection","id":"90ad4074-8766-494a-b16d-ad3c009f6e9c","organizationId":"xxxxxxxxxxxxxxx","name":"Sistemisti","externalId":null}]

As per docs and examples i've found this should do the job:
echo '["90ad4074-8766-494a-b16d-ad3c009f6e9c"]' | bw encode |  bw edit item-collection e4a8bb02-3696-4664-978d-ad3d01293bc8 

but i always get the error:
Unknown object.

Any tips?

thsnks

**Comment by eliykat** [comment]
Thanks for getting in touch! We use GitHub issues as a place to track bugs and other development related issues. If you'd like help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
