### ISSUE TITLE
Changes to CLI authentication? (Additional authentication required)

### ISSUE THREAD

**Issue by gingerlime** [bitwarden/cli#383]
## Describe the Bug

Changes to CLI authentication? (Additional authentication required)

## Steps To Reproduce

We've been using the Bitwarden CLI for some time now to manage our server secrets (using [envwarden](https://github.com/envwarden/envwarden/), which I created). Today we're suddenly seeing some strange behaviour when using `bw login`

```
user@server:~# bw login
? Email address: email@address.com
? Master password: [hidden]
? Additional authentication required.
API key client_secret:
```

We use an organization account, and we're a paying customer on the hosted version of Bitwarden.

Also having trouble using the --apikey option.

```
# bw login --apikey
? client_id:  ************
? client_secret: **************
{"response":{"error":"invalid_client"},"captchaRequired":false,"statusCode":400}
```

## Expected Result

Same as yesterday and the last few years? it should work if authentication is successful, be it using email/password, apikey or otherwise. Our password is super long and complex, so even stronger than any client_secret already.

## Actual Result

See above

## Environment

- Operating system: Ubuntu 20.04
- Shell: bash
- Build Version (run `bw --version`): 1.18.1

**Comment by kspearrin** [comment]
@gingerlime Thanks for the feedback, and really sorry that this has effected your existing workflows. Given that we don't know if you have a strong master password or not, captcha was a solution to the constant automated brute force attacks that we see on our authentication endpoints. API key authentication via the CLI has been around for quite a while and will bypass the need to use a captcha. I recommend adjusting your workflow to use an API key rather than username and password.

**Comment by gingerlime** [comment]
> This captcha challenge is required to authenticate if Cloudflare indicates to us your request is likely coming from a bot (here's the code where we do that).

Wouldn't Cloudflare likely classify all CLI requests as a bot? it's not a normal browser, but rather a custom API client with custom user-agent etc. I'm not entirely sure how Cloudflare's bot protection works, but off the top of my head, it seems like it might not be the best solution to protecting the CLI from bots. I would imagine it fits protection for sites which are typically accessed by regular browsers?

**Comment by gingerlime** [comment]
Yes, I understand. I wish there was an option on the account/user to say "I have a secure password, please bypass Captcha for me", rather than having to change the whole workflow to use an api client id, secret and master password, especially when it offers no security benefit for me as a user of the API.

As the creator/maintainer of [envwarden](https://github.com/envwarden/envwarden/), this also poses a challenge for backwards compatibility.

As a customer of Bitwarden, it also means updating our automated workflows, which adds quite a bit of overhead for something that JustWorked before ... :)

**Comment by micottis** [comment]
@jdecaron did you try `bw unlock` after `bw login --apikey`? That command will ask for your password and then give you the session key which you can use to retrieve your items (without having to enter any password or key or 2FA code).

**Comment by MGibson1** [comment]
This issue is remediated by bitwarden/server#1626. Interactive sessions now prompt for api key with master password only on the first login of a device.

> Note: this server version is not yet released

Until now, we didn't have a good reason to differentiate when to use api keys and when to use username/password other than unlocking. I think we have a good case now to suggest flows which need predictable prompts to use api key authentication + unlock with master password vs direct user interface with CLI using username master password. I'll make sure our documentation is updated to reflect these new recommendations.

I think all-in-all, this is more in line with expected behavior when authorizing external applications to interact with your Bitwarden account _and_ significantly improves account security for all users by reducing the ability to brute-force

**Comment by r3k2** [comment]
WTF all our work just stop working because of stupid cloudflare? seriously? is there is a fix for this yet? we need bw login to work ASAP
