### ISSUE TITLE
Download attachments using snap version of bw cli

### ISSUE THREAD

**Issue by toxic0berliner** [bitwarden/cli#412]
using ubuntu, installed bw cli using snap, I am unable to download attachments.

I first got this error : 
````
$ bw get attachment myattachment.png --itemid myItemId
Cannot save file to /var/lib/snapd/void/myattachment.png
````
I then tried with --output : 

````
$ bw get attachment myattachment.png --itemid myItemId --output /tmp/delme
Saved /tmp/delme/myattachment.png
$ ls -lh /tmp/delme
total 0
````
Nothing got stored...

Any idea as to why and if this can be fixed somehow ?

Thanks in advance for any help.

**Comment by sso-bitwarden** [comment]
Please try

bw get attachment myattachment.png --itemid myItemId --output /tmp/delme/

**Comment by toxic0berliner** [comment]
I already did, that's my second attempt, it says it stored something but there's nothing there, couldn't find the file anywhere...

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
