### ISSUE TITLE
bw login - No user id found or request comes from a bot

### ISSUE THREAD

**Issue by vitalirybinskia** [bitwarden/cli#418]
1. If I try to login using apikey I get an error "No user id found"

`$env:BITWARDENCLI_APPDATA_DIR=".\"`
`$env:BW_CLIENTID = $client_id`
`$env:BW_CLIENTSECRET = $client_secret`

`$bw = (Get-Command '.\bw').Source`

`& $bw login --apikey`

2. If I use 
`& $bw login $username $masterPass --raw`

I get "Your authentication request appears to be coming from a bot
Please use your API key to validate this request and ensure BW_CLIENTSECRET is correct, if set."

## Environment

- Operating system: Windows 10 21H2
- Shell: PowerShell 5
- Build Version: 1.19.1

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by vitalirybinskia** [comment]
"The No user id found error would be normal if you used the Organization API key. Are you using the client_id for the Organization itself? An API key for the Organization would not work. If the client_id begins with organization.xxxxxx, the bw operation will fail. You'll want to log in as the @altoros.com. account and go to that user's Settings and use their API key that begins with client.xxxxxx. "
@eliykat Thanks a lot!
