### ISSUE TITLE
bw CLI sync without unlocking

### ISSUE THREAD

**Issue by IpsmLorem** [bitwarden/cli#423]
Hi.

I don't really know if this is abug of a feature request. I need to autmate backup from bitwarden and I though I could do that with the BW CLI.
- BW login with personnal API
- BW sync and backup the cli data

But sync forces me to unlock first. I don't need decrypted vault, why prompting for the password to sync data ? Did I missed something ?

**Comment by eliykat** [comment]
Hi @IpsmLorem, I think this is a question best directed to our Customer Success team. We use GitHub issues as a place to track bugs and other development related issues. If you'd like help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
