### ISSUE TITLE
CLI login with  API key fails with "invalid client" error

### ISSUE THREAD

**Issue by kintrupf** [bitwarden/cli#442]
## Describe the Bug
If I try to unlock my vault with my user API key I get the error "invalid client". I'm using the latest version of the CLI client.
I've set the client ID and client secret as environment variables and made sure that there is no leading or trailing white space.

## Actual Result
"client error"

## Screenshots or Videos
![image](https://user-images.githubusercontent.com/8496344/148932757-8fb2b62e-3875-4956-a176-3bec5b3492f4.png)

## Environment
Windows 10
Command line client 1.20.0

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We've been unable to reproduce this, but we'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
