### ISSUE TITLE
Error CLI and APP

### ISSUE THREAD

**Issue by fr3d02** [bitwarden/cli#458]
Hello, 

I've problems with CLI and Bitwarden APP (It's Okey with Web interface). 
![image](https://user-images.githubusercontent.com/27649519/151810860-91606fd7-9958-4977-8069-5cf39bc6b486.png)
![image](https://user-images.githubusercontent.com/27649519/151811077-226ddbb0-4c15-4ee6-aed9-27585d2c3753.png)

Have you any idea ?

Thanks a lot.

**Comment by eliykat** [comment]
Hi @fr3d02, it looks like you're having trouble reaching your self-hosted instance. We use GitHub issues as a place to track bugs and other development related issues. If you'd like help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
