### ISSUE TITLE
Can't login with API Key

### ISSUE THREAD

**Issue by Titancube** [bitwarden/cli#460]
## Describe the Bug

Cannot login with apikey

## Steps To Reproduce

1. launch through `bw login --apikey`
2. copy or handtype client_id and client_secret

## Expected Result

Login with api key

## Actual Result

Returns `{"response":null, "statusCode": 403}`

## Environment

- Operating system: macOS 12.2 Monterey with M1 chip
- Shell: zsh
- Build Version (run `bw --version`): 1.20.0

## Additional Context

also it does not work in min browser

**Comment by eliykat** [comment]
This sounds like a networking or configuration issue. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk and our Customer Success team will help you debug it.
