### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by AmbassadorLaZer** [bitwarden/cli#463]
Whenever I open the CLI, it opens the CMD then a quick flash of text appears and instantly closes.

This is my first time installing the CLI.

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
