### ISSUE TITLE
Export seems to only check password locally

### ISSUE THREAD

**Issue by dprzybylo** [bitwarden/cli#69]
The export feature requires you to enter your master password before you can export. However, it seems this is only checked locally against a previously hashed password. If a vault were unlocked, a threat actor could potentially find a way to set these two values equal to initiate a mass export without providing the master password.

This may be an issue with other forms of the app (not just the CLI).

**Comment by kspearrin** [comment]
This is how all of the Bitwarden applications behave. The password prompt on export is just a safety check so that someone cannot quickly export the data to a file from someone's workstation. An unlocked vault already holds unencrypted data in memory, as well as encryption keys, so a malicious actor that knows what they are doing can already compromise that data whether the convenient export function is available or not.

**Comment by dprzybylo** [comment]
That’s fair. Thanks.
